name: arrow_pad
description: A circular pad with 4 arrows which has a functionality of 4 buttons.
version: 0.1.5
# homepage: https://github.com/immadisairaj/arrow_pad
repository: https://github.com/immadisairaj/arrow_pad

screenshots:
  - description: 'Default Arrow Pad'
    path: example/screenshots/arrow_pad.png

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
